######################################################################
# Automatically generated by qmake (2.01a) mer. janv. 30 18:58:52 2008
######################################################################

CONFIG -= app_bundle
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ButtonCount.h
SOURCES += ButtonCount.cpp main.cpp
