######################################################################
# Automatically generated by qmake (2.01a) mer. janv. 30 18:58:52 2008
######################################################################



# Input
HEADERS += ButtonCount.h MyLCD.h \
    myWindow.h
SOURCES += ButtonCount.cpp MyLCD.cpp main.cpp \
    myWindow.cpp
