######################################################################
# Automatically generated by qmake (2.01a) ven. janv. 15 11:16:50 2010
######################################################################
CONFIG -= app_bundle
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
